SEED: 42
num_classes: 100
data_name: cifar100
data_params:
  algo: dare
  data_dir: datasets/cifar100
  batch_size: 512
  num_workers: 3
  image_size: 32
return_logs: False
eval_every: 10
n_epochs: &epoch 500
n_epochs_mlp: 100
gpu_id: 1
opt: SGD
opt_params:
  lr: !!float 5e-1
  momentum: 0.9
  nesterov: True
# schedular_params:
#   step_size: 40 
#   gamma: 0.1
schedular_params:
  T_max: *epoch 
  eta_min: 0.001
mlp_opt: SGD
mlp_opt_params:
  lr: !!float 0.01
  momentum: 0.9
  nesterov: True
model_params:
  model_name: 'resnet18' 
  pretrained: False 
  proj_dim: 128
mlp_type: "hidden"
loss: dare
loss_params: 
  sim: 'cosine'
  tau: 0.5
  lambd: 0.9
vae_linear_out: 256
distributed: False
train_algo: dare