SEED: 42
num_classes: 10
data_name: cifar10
data_params:
  algo: simsiam
  data_dir: datasets/cifar10
  batch_size: 512
  num_workers: 3
  image_size: 32
return_logs: False
eval_every: 10
n_epochs: &epoch 350
n_epochs_mlp: 100
gpu_id: 2
opt: SGD
opt_params:
  lr: !!float 5e-1
  momentum: 0.9
# schedular_params:
#   step_size: 40 
#   gamma: 0.1
schedular_params:
  T_max: *epoch 
  eta_min: 0.001
mlp_opt: SGD
mlp_opt_params:
  lr: !!float 0.01
  momentum: 0.9
model_params:
  model_name: 'resnet50' 
  pretrained: True 
  proj_dim: 128
  algo_type: 'simsiam'
  pred_dim: 512
mlp_type: "hidden"
loss: simsiam
distributed: False
train_algo: simsiam