SEED: 42
num_classes: 100
data_name: cifar100
data_params:
  algo: simsiam
  data_dir: datasets/cifar100
  batch_size: 512
  num_workers: 3
  image_size: 32
return_logs: False
eval_every: 10
n_epochs: &epoch 800
n_epochs_mlp: 100
gpu_id: 1
opt: SGD
opt_params:
  lr: !!float 6e-2
  momentum: 0.9
  weight_decay: !!float 1e-4
# schedular_params:
#   step_size: 40 
#   gamma: 0.1
schedular_params:
  T_max: *epoch 
  eta_min: 0.001
mlp_opt: SGD
mlp_opt_params:
  lr: !!float 30
  momentum: 0.9
mlp_schedular_params:
  step_size: 20
  gamma: 0.1
model_params:
  model_name: 'resnet50' 
  pretrained: False 
  proj_dim: 128
  algo_type: 'simsiam'
  pred_dim: 512
mlp_type: "hidden"
loss: simsiam
distributed: False
train_algo: simsiam