SEED: 42
num_classes: 10
data_name: cifar10
data_params:
  algo: supcon
  data_dir: datasets/cifar10
  batch_size: 1024
  num_workers: 3
  image_size: 32
return_logs: False
eval_every: 10
n_epochs: 200
gpu_id: 0
opt: SGD
opt_params:
  lr: !!float 8e-1
  momentum: 0.9
schedular_params:
  step_size: 40 
  gamma: 0.1
mlp_opt: SGD
mlp_opt_params:
  lr: !!float 1e-3
  momentum: 0.9
model_params:
  model_name: 'resnet50' 
  pretrained: True 
  proj_dim: 128
loss: supcon
loss_params: 
  sim: 'cosine'
  tau: 0.1
distributed: False
train_algo: supcon