SEED: 42
num_classes: 10
data_name: cifar10
data_params:
  algo: triplet
  data_dir: datasets/cifar10
  batch_size: 512
  num_workers: 3
  image_size: 32
return_logs: False
eval_every: 10
n_epochs: &epoch 350
n_epochs_mlp: 100
gpu_id: 3
opt: SGD
opt_params:
  lr: !!float 1e-2
  momentum: 0.9
  nesterov: True
# schedular_params:
#   step_size: 40 
#   gamma: 0.1
schedular_params:
  T_max: *epoch 
  eta_min: 0.0001
mlp_opt: SGD
mlp_opt_params:
  lr: !!float 0.01
  momentum: 0.9
  nesterov: True
model_params:
  model_name: 'resnet50' 
  pretrained: False 
  proj_dim: 128
mlp_type: "hidden"
loss: triplet
loss_params: 
  margin: 1.0
distributed: False
train_algo: triplet